# Generated by Django 4.2 on 2023-05-09 19:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports24h', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='received_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_user',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports24h.country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='favorite_sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports24h.sport'),
        ),
        migrations.AlterField(
            model_name='client',
            name='favorite_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports24h.team'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='followsforum',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports24h.country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports24h.product'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports24h.country'),
        ),
    ]
