# Generated by Django 4.2.1 on 2023-05-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports24h', '0002_rename_text_message_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='product',
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='default-user-icon.png', upload_to='users'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='photo',
            field=models.ImageField(default='default-user-icon.png', upload_to='users'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sports24h.seller'),
        ),
        migrations.AddField(
            model_name='seller',
            name='photo',
            field=models.ImageField(default='default-user-icon.png', upload_to='users'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default-product-image.png', upload_to='products'),
        ),
    ]
