# Generated by Django 4.2.1 on 2023-05-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports24h', '0003_size_remove_post_is_active_remove_post_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sports24h.forum'),
            preserve_default=False,
        ),
    ]
